---
provision:
  os: "rhel"
  stage: "base"
  provider: "aws"
sync: []
actions:
  - type: "script"
    title: "build origin-metrics release"
    repository: "origin-metrics"
    script: |-
      git_branch=$( git rev-parse --abbrev-ref HEAD )
      echo "Building origin-metrics images on git branch $git_branch"
      hack/build-images.sh
  - type: "script"
    title: "create directory for docker config"
    script: |-
      mkdir -p /tmp/.docker
      chmod a+rwx /tmp/.docker
  - type: "host_script"
    title: "transfer docker config to remote host"
    script: |-
      scp -F ${WORKSPACE}/.config/origin-ci-tool/inventory/.ssh_config /var/lib/jenkins/.docker/config.json openshiftdevel:/tmp/.docker/
  - type: "script"
    title: "push origin-metrics release"
    repository: "origin-metrics"
    script: |-
      sudo chmod a+rw /tmp/.docker/config.json
      git_branch=$( git rev-parse --abbrev-ref HEAD )
      if [[ $git_branch == master ]]; then
        echo "Pushing origin-metrics images release git branch:'${git_branch}', docker tag:'latest'"
        OS_PUSH_BASE_REGISTRY="docker.io/" DOCKER_CONFIG=/tmp/.docker hack/push-release.sh
      elif [[ $git_branch =~ release-* ]]; then
        echo "Pushing origin-metrics images release git branch:'${git_branch}', docker tag:'v${git_branch#release-}'"
        OS_PUSH_BASE_REGISTRY="docker.io/" DOCKER_CONFIG=/tmp/.docker OS_PUSH_TAG="v${git_branch#release-}" hack/push-release.sh
      fi
      sudo rm -rf /tmp/.docker
