---
parent: 'common/test_cases/origin_built_release.yml'
overrides:
  junit_analysis: True
  timer: 'H H * * *'
  email:
    - bparees@redhat.com
    - cewong@redhat.com
    - gmontero@redhat.com
    - cdaley@redhat.com
    - miminar@redhat.com
    - obulatov@redhat.com
    - agladkov@redhat.com
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        export ORIGIN_COMMIT=$(git log -1 --pretty=%h)
        test/extended/clusterup.sh
