---
parent: 'common/test_cases/origin_minimal.yml'
overrides:
  junit_analysis: False
  email:
    - jpeeler@redhat.com
extensions:
  actions:
    - type: "script"
      title: "determine the release commit for origin images"
      repository: "origin"
      script: |-
        jobs_repo="/data/src/github.com/openshift/aos-cd-jobs/"
        export ORIGIN_COMMIT=$(git log -1 --pretty=%h)
        echo $ORIGIN_COMMIT > "${jobs_repo}/ORIGIN_COMMIT"
        source hack/lib/init.sh
        export ORIGIN_BUILT_VERSION=$(os::build::rpm::format_nvra)
        echo $ORIGIN_BUILT_VERSION > "${jobs_repo}/ORIGIN_BUILT_VERSION"
    - type: "script"
      title: "build Origin"
      repository: "origin"
      timeout: 1800
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64 hack/env make build
    - type: "script"
      title: "build service-catalog user-broker image"
      repository: "origin"
      timeout: 1800
      script: |-
        REGISTRY=openshift/ NO_DOCKER=1 make -C cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog user-broker-image
    - type: "script"
      title: "build Service Catalog binary"
      repository: "origin"
      timeout: 1800
      script: |-
        unset GOPATH; cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/hack/build-go.sh
    - type: "script"
      title: "run Service Catalog unit tests"
      repository: "origin"
      timeout: 1800
      script: |-
        NO_DOCKER=1 make -C cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog test-unit
    - type: "script"
      title: "run Service Catalog integration tests"
      repository: "origin"
      timeout: 2700
      script: |-
        sudo yum -y install etcd
        # switch to wget since curl is using NSS - https://github.com/kubernetes/kubernetes/pull/59966 (can be removed once 0.1.9+ vendored)
        curl --version
        wget --version
        sed -i 's/curl --cacert/wget --ca-certificate/' cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/contrib/hack/start-server.sh
        # reduces flakes - can be removed once 0.1.9+ is vendored
        sed -i -r 's/(.*)(wait.ForeverTestTimeout)(.*)/\1\2*5\3/' cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/test/util/util.go
        NO_DOCKER=1 make -C cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog scBuildImageTarget=.scBuildImage test-integration
    - type: "script"
      title: "build Service Catalog image"
      repository: "origin"
      timeout: 1800
      script: |-
        hack/build-local-images.py service-catalog
    - type: "script"
      title: "build origin images"
      repository: "origin"
      timeout: 1800
      script: |-
        hack/build-local-images.py
    - type: "script"
      title: "build Service Catalog E2E test binary"
      repository: "origin"
      timeout: 1800
      script: |-
        NO_DOCKER=1 make -C cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog bin/e2e.test
    - type: "script"
      title: "start cluster with Service Catalog"
      repository: "origin"
      timeout: 1800
      script: |-
        if [[ "${PULL_BASE_REF:-master}" == "release-3.9" ]]; then
          ./_output/local/bin/linux/amd64/oc cluster up --loglevel=5 --version=latest --service-catalog
        else
          ./_output/local/bin/linux/amd64/oc cluster up --loglevel=5 --tag=latest --service-catalog
        fi
        ./_output/local/bin/linux/amd64/oc login -u system:admin
        ./_output/local/bin/linux/amd64/oc describe po --all-namespaces
    - type: "script"
      title: "Run Service Catalog E2E"
      repository: "origin"
      timeout: 1800
      script: |-
        kubeconfig=$(mktemp)
        ./_output/local/bin/linux/amd64/oc config view --raw > $kubeconfig
        chmod a+rw $kubeconfig
        export KUBECONFIG=$kubeconfig
        SERVICECATALOGCONFIG=$KUBECONFIG cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/bin/e2e.test -v 10 -alsologtostderr -broker-image openshift/user-broker:canary
        rm -f $kubeconfig
  generated_artifacts:
    catalog-apiserver.log: '/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc login -u system:admin && /data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/kubectl logs -n kube-service-catalog -lapp=apiserver -c apiserver'
    catalog-controller.log: '/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc login -u system:admin && /data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/kubectl logs -n kube-service-catalog -lapp=controller-manager'
  system_journals:
    - origin-master.service
    - origin-master-api.service
    - origin-master-controllers.service
    - origin-node.service
    - openvswitch.service
    - ovs-vswitchd.service
    - ovsdb-server.service
    - etcd.service
