---
parent: 'common/test_cases/crio.yml'
overrides:
  provision:
    os: "rhel"
    stage: "crio"
    provider: "aws"
extensions:
  actions:
  - type: "forward_parameters"
    parameters:
      - PULL_NUMBER
      - PULL_BASE_SHA
      - PULL_PULL_SHA
  - type: "script"
    title: "clone cri-o and check out the correct refs"
    script: |-
      cd /go/src/github.com/kubernetes-sigs/cri-o
      git fetch origin
      git checkout master
      git branch -D target || true
      git branch -D pr || true
      git branch target "${PULL_BASE_SHA}"
      git checkout target
      git fetch origin "pull/${PULL_NUMBER}/head:pr"
      git merge "${PULL_PULL_SHA}"
  - type: "script"
    title: "run the cri-o e2e features tests"
    timeout: "21600"  # 6 hours.  Playbook has shorter timeout for the test-task.
    script: |-
      ansible-playbook -vv --become  \
                       -i localhost, \
                       --tags e2e-features    \
                       --become-user root \
                       --connection local \
                       /go/src/github.com/kubernetes-sigs/cri-o/contrib/test/integration/main.yml
