---
parent: 'common/test_cases/origin.yml'
overrides:
  sync_repos:
    - name: "image-registry"
extensions:
  actions:
    - type: "script"
      title: "run image-registry integration tests"
      repository: "image-registry"
      script: |-
        make test-integration
