---
parent: 'common/test_cases/origin_built_release.yml'
overrides:
  junit_analysis: False
  timer: 'H H * * *'
  email:
    - jpeeler@redhat.com
extensions:
  actions:
    - type: "script"
      title: "determine the release commit for origin images"
      repository: "origin"
      script: |-
        jobs_repo="/data/src/github.com/openshift/aos-cd-jobs/"
        git log -1 --pretty=%h > "${jobs_repo}/ORIGIN_COMMIT"
        source hack/lib/init.sh
        os::build::rpm::format_nvra > "${jobs_repo}/ORIGIN_BUILT_VERSION"
    - type: "script"
      title: "build junitreport"
      repository: "origin"
      timeout: 1800
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64/junitreport hack/env make build WHAT=tools/junitreport
    - type: "script"
      title: "build service-catalog user-broker image"
      repository: "origin"
      timeout: 1800
      script: |-
        REGISTRY=openshift/ NO_DOCKER=1 make -C cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog user-broker-image
    - type: "script"
      title: "build Service Catalog binary"
      repository: "origin"
      timeout: 1800
      script: |-
        unset GOPATH; cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/hack/build-go.sh
    - type: "script"
      title: "run Service Catalog unit tests"
      repository: "origin"
      timeout: 1800
      script: |-
        NO_DOCKER=1 make -C cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog test-unit
    - type: "script"
      title: "run Service Catalog integration tests"
      repository: "origin"
      timeout: 1800
      script: |-
        sudo yum -y install etcd
        # this strips the -i arg to "go test". can be dropped once PR is merged:
        # https://github.com/kubernetes-incubator/service-catalog/pull/1566 (and vendored in rebase)
        sed -i 's/\(go test.*\)\( -i \)\(.*\)/\1 \3/' cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/test/integration.sh
        NO_DOCKER=1 make -C cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog scBuildImageTarget=.scBuildImage test-integration
    - type: "script"
      title: "build Service Catalog image"
      repository: "origin"
      timeout: 1800
      script: |-
        hack/build-local-images.py service-catalog
    - type: "script"
      title: "build Service Catalog E2E test binary"
      repository: "origin"
      timeout: 1800
      script: |-
        NO_DOCKER=1 make -C cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog bin/e2e.test
    - type: "script"
      title: "start cluster with Service Catalog"
      repository: "origin"
      timeout: 1800
      script: |-
        ./_output/local/bin/linux/amd64/oc cluster up --version=latest --service-catalog
    - type: "script"
      title: "Run Service Catalog E2E"
      repository: "origin"
      timeout: 1800
      script: |-
        ./_output/local/bin/linux/amd64/oc login -u system:admin
        kubeconfig=$(mktemp)
        ./_output/local/bin/linux/amd64/oc config view --raw > $kubeconfig
        chmod a+rw $kubeconfig
        export KUBECONFIG=$kubeconfig
        SERVICECATALOGCONFIG=$KUBECONFIG cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/bin/e2e.test -v 10 -alsologtostderr -broker-image openshift/user-broker:canary
        rm -f $kubeconfig
  system_journals:
    - origin-master.service
    - origin-master-api.service
    - origin-master-controllers.service
    - origin-node.service
    - openvswitch.service
    - ovs-vswitchd.service
    - ovsdb-server.service
    - etcd.service
