---
parent: 'common/test_cases/origin_installed_release.yml'
extensions:
  actions:
    - type: "script"
      title: "build the jenkins plugin and test image"
      repository: "jenkins-plugin"
      script: |-
        export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
        mvn package
        cd PR-Testing
        ./build-jenkins-plugin-snapshot-image.sh
    - type: "script"
      title: "test the jenkins plugin test image against origin"
      repository: "origin"
      script: |-
        KUBECONFIG=/etc/origin/master/admin.kubeconfig USE_SNAPSHOT_JENKINS_IMAGE=1 TEST_ONLY=true JUNIT_REPORT='true' make test-extended SUITE=core FOCUS="openshift pipeline plugin"