---
parent: 'test_cases/test_pull_request_openshift_ansible_extended_conformance_install.yml'
overrides:
  junit_analysis: True
  sync:
    - "openshift,origin=master"
    - "openshift,aos-cd-jobs=master"
    - "openshift,image-registry=master"
    - "openshift,kubernetes-metrics-server=master"
    - "openshift,origin-web-console-server=master"
extensions:
  actions:
    - type: "host_script"
      title: "check other job statuses"
      script: |-
        if [[ -n "${PULL_REFS:-}" ]]; then
          export OPENSHIFT_ANSIBLE_TARGET_BRANCH="${PULL_REFS%%:*}"
        fi
        scp -F ${WORKSPACE}/.config/origin-ci-tool/inventory/.ssh_config openshiftdevel:/data/src/github.com/openshift/aos-cd-jobs/sjb/check-pull-request-status.py .
        scp -F ${WORKSPACE}/.config/origin-ci-tool/inventory/.ssh_config openshiftdevel:/data/src/github.com/openshift/aos-cd-jobs/sjb/test_status_config.yml .
        python check-pull-request-status.py "${OPENSHIFT_ANSIBLE_PULL_ID}" "${OPENSHIFT_ANSIBLE_TARGET_BRANCH}" /var/lib/jenkins/.config/hub test_status_config.yml
