---
parent: 'common/test_cases/origin_built_release.yml'
overrides:
  timer: 'H H * * *'
  email:
    - bparees@redhat.com
    - cewong@redhat.com
    - gmontero@redhat.com
    - rymurphy@redhat.com
    - cdaley@redhat.com
    - jminter@redhat.com
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        JUNIT_REPORT='true' make test-extended SUITE=core FOCUS="\[builds\]"