---
parent: 'common/test_cases/origin.yml'
overrides:
  junit_analysis: False
  email:
    - jpeeler@redhat.com
    - jaboyd@redhat.com
extensions:
  sync_repos:
    - name: "origin"
    - name: "service-catalog"
  actions:
    - type: "script"
      title: "determine the release commit for origin images"
      repository: "origin"
      script: |-
        jobs_repo="/data/src/github.com/openshift/aos-cd-jobs/"
        export ORIGIN_COMMIT=$(git log -1 --pretty=%h)
        echo $ORIGIN_COMMIT > "${jobs_repo}/ORIGIN_COMMIT"
        source hack/lib/init.sh
        export ORIGIN_BUILT_VERSION=$(os::build::rpm::format_nvra)
        echo $ORIGIN_BUILT_VERSION > "${jobs_repo}/ORIGIN_BUILT_VERSION"
    - type: "script"
      title: "build Origin"
      repository: "origin"
      timeout: 1800
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64 hack/env make build
    - type: "script"
      title: "build service-catalog user-broker image"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        REGISTRY=openshift/ make -f Makefile.sc user-broker-image
    - type: "script"
      title: "build Service Catalog binary"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        hack/env make build
    - type: "script"
      title: "run Service Catalog unit tests"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        # the preserve directory is not used here, so include a constant file to avoid copy failures
        OS_BUILD_ENV_PRESERVE="Makefile" hack/env NO_DOCKER=1 make -f Makefile.sc test-unit
    - type: "script"
      title: "build Service Catalog integration test binary"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        OS_BUILD_ENV_PRESERVE=integration.test hack/env NO_DOCKER=1 make -f Makefile.sc build-integration
    - type: "script"
      title: "Run Service Catalog integration tests"
      repository: "service-catalog"
      timeout: 2700
      script: |-
        sudo yum -y install etcd
        ./integration.test -test.v -alsologtostderr -v 9
    - type: "script"
      title: "build Service Catalog image"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        hack/env hack/build-source-image.sh
        hack/env make build-images
    - type: "script"
      title: "build origin images"
      repository: "origin"
      timeout: 1800
      script: |-
        hack/build-local-images.py
    - type: "script"
      title: "build Service Catalog E2E test binary"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        sudo chown $USER:$USER bin
        OS_BUILD_ENV_PRESERVE=bin/ hack/env NO_DOCKER=1 make -f Makefile.sc bin/e2e.test
    - type: "script"
      title: "start cluster with Service Catalog"
      repository: "origin"
      timeout: 1800
      script: |-
        if [[ "${PULL_BASE_REF:-master}" == "release-3.9" ]]; then
          ./_output/local/bin/linux/amd64/oc cluster up --loglevel=5 --version=latest --service-catalog
        else
          ./_output/local/bin/linux/amd64/oc cluster up --loglevel=5 --image='openshift/origin-${component}:'"$( cat ./ORIGIN_COMMIT )" --enable=service-catalog
        fi
        ./_output/local/bin/linux/amd64/oc login -u system:admin
        ./_output/local/bin/linux/amd64/oc describe po --all-namespaces
    - type: "script"
      title: "Run Service Catalog E2E"
      repository: "service-catalog"
      timeout: 900
      script: |-
        export KUBECONFIG=~/.kube/config
        SERVICECATALOGCONFIG=$KUBECONFIG bin/e2e.test -v 10 -alsologtostderr -broker-image openshift/user-broker:canary
  post_actions:
    - type: "script"
      title: "grab container logs"
      repository: "origin"
      script: |
        trap 'exit 0' EXIT
        ( source hack/lib/init.sh; os::cleanup::dump_container_logs )
  generated_artifacts:
    catalog-apiserver.log: '/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc login -u system:admin && /data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/kubectl logs -n kube-service-catalog -lapp=apiserver -c apiserver'
    catalog-controller.log: '/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc login -u system:admin && /data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/kubectl logs -n kube-service-catalog -lapp=controller-manager'
  system_journals:
    - origin-master.service
    - origin-master-api.service
    - origin-master-controllers.service
    - origin-node.service
    - openvswitch.service
    - ovs-vswitchd.service
    - ovsdb-server.service
    - etcd.service
