---
parent: 'common/test_cases/origin_release.yml'
overrides:
  junit_analysis: False
extensions:
  actions:
    - type: "script"
      title: "determine the release commit for origin images and version for rpms"
      repository: "origin"
      script: |-
        registry_repo="/data/src/github.com/openshift/image-registry/"
        git log -1 --pretty=%h >> "${registry_repo}/ORIGIN_COMMIT"
    - type: "script"
      title: "build the image registry container image"
      repository: "image-registry"
      timeout: 3600
      script: |-
        if [[ "${PULL_BASE_REF}" == "master" || "${PULL_BASE_REF}" == "release-3.7" || "${PULL_BASE_REF}" == "release-3.8" ]]; then
          make build-images
          docker tag openshift/origin-docker-registry:latest "openshift/origin-docker-registry:$( cat ./ORIGIN_COMMIT )"
        fi
    - type: "script"
      title: "run end-to-end tests"
      repository: "origin"
      timeout: 7200
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64/end-to-end.test hack/env make build-router-e2e-test
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64/etcdhelper hack/env make build WHAT=tools/etcdhelper
        OPENSHIFT_SKIP_BUILD='true' JUNIT_REPORT='true' make test-end-to-end -o build