---
parent: 'common/test_cases/origin_release_with_ecosystem_310.yml'
overrides:
  junit_analysis: False
  email:
    - aos-auth-team@redhat.com
  sync:
    - "openshift,origin=release-3.10"
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        OPENSHIFT_SKIP_BUILD='true' JUNIT_REPORT='true' make test-extended SUITE=ldap_groups
