---
parent: 'common/test_cases/origin_release_install_azure_39.yml'
overrides:
  email:
  - aos-azure@redhat.com
extensions:
  parameters:
    - name: "SUITE"
      description: "Which shell file in the <a href='https://github.com/openshift/origin/tree/master/test/extended'><code>origin/test/extended/</code></a> di
rectory to run."
      default_value: "conformance"
  actions:
    - type: "script"
      title: "run tests"
      timeout: 900
      script: |-
        exit 0
