---
parent: 'common/test_cases/origin_installed_release.yml'
overrides:
  junit_analysis: True
  timer: 'H H * * *'
  email:
    - bparees@redhat.com
    - cewong@redhat.com
    - gmontero@redhat.com
    - cdaley@redhat.com
    - miminar@redhat.com
    - obulatov@redhat.com
    - agladkov@redhat.com
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64/extended.test hack/env make build-extended-test
        OPENSHIFT_SKIP_BUILD='true' KUBECONFIG=/etc/origin/master/admin.kubeconfig TEST_ONLY=true JUNIT_REPORT='true' make test-extended SUITE=core FOCUS="\[Feature:Builds\]"
