---
parent: 'common/test_cases/origin_built_release.yml'
overrides:
  junit_analysis: False
  email:
    - skuznets@redhat.com
    - deads2k@redhat.com
    - jliggitt@redhat.com
    - mkhan@redhat.com
    - ssorce@redhat.com
    - aos-security-team@redhat.com
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64/extended.test hack/env make build-extended-test
        OPENSHIFT_SKIP_BUILD='true' JUNIT_REPORT='true' make test-extended SUITE=ldap_groups
