---
parent: 'common/test_cases/origin.yml'
extensions:
  actions:
    - type: "script"
      title: "run test-cmd"
      repository: "origin"
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/scripts hack/env JUNIT_REPORT='true' make test-cmd -k