---
parent: 'common/test_cases/origin_built_installed_release.yml'
overrides:
  sync:
    - "openshift,origin=master"
    - "openshift,aos-cd-jobs=master"
    - "openshift,image-registry=master"
    - "openshift,origin-aggregated-logging=master"
    - "openshift,kubernetes-metrics-server=master"
    - "openshift,origin-web-console-server=master"
  evars: "-e skip_sanity_checks=true -e openshift_disable_check=* -e openshift_docker_log_driver=json-file -e openshift_docker_options=--log-driver=json-file -e openshift_install_examples=false"
extensions:
  actions:
    - type: "script"
      title: "build an origin-aggregated-logging release"
      repository: "origin-aggregated-logging"
      script: |-
        if [[ "${REPO_NAME:-}" == "openshift-ansible" ]]; then
          if [[ -n "${PULL_REFS:-}" ]]; then
            export OPENSHIFT_ANSIBLE_TARGET_BRANCH="${PULL_REFS%%:*}"
          fi
          git checkout ${OPENSHIFT_ANSIBLE_TARGET_BRANCH}
        fi
        hack/build-images.sh
    - type: "script"
      title: "install origin-aggregated-logging"
      repository: "aos-cd-jobs"
      script: |-
        playbook_base='/usr/share/ansible/openshift-ansible/playbooks/'
        if [[ -s "${playbook_base}openshift-logging/config.yml" ]]; then
            playbook="${playbook_base}openshift-logging/config.yml"
        else
            playbook="${playbook_base}byo/openshift-cluster/openshift-logging.yml"
        fi
        pushd "/data/src/github.com/openshift/origin-aggregated-logging/"
        curbranch=$( git rev-parse --abbrev-ref HEAD )
        # os::build::image tags with both "latest" and the release_commit
        release_commit="$( git log -1 --pretty=%h )"
        popd
        logging_extras=""
        if [[ "${PULL_REFS%%:*}" == es5.x ]]; then
            logging_extras="${logging_extras} -e openshift_logging_es5_techpreview=True \
                            -e openshift_logging_image_version=latest"
        elif [[ "${curbranch}" == master ]]; then
            # force image version/tag to be latest, otherwise it will use openshift_tag_version
            logging_extras="${logging_extras} -e openshift_logging_image_version=latest"
        fi
        #                          -e openshift_logging_install_eventrouter=True                            \
        # richm 20171205 - ansible "too much recursion" bug
        ansible-playbook -vv --become               \
                         --become-user root         \
                         --connection local         \
                         --inventory sjb/inventory/ \
                         -e openshift_deployment_type=origin  \
                         -e openshift_logging_install_logging=True \
                         -e debug_level=2           \
                         -e openshift_logging_image_prefix="openshift/origin-" \
                         -e openshift_logging_image_version="${release_commit:-latest}" \
                         -e openshift_logging_elasticsearch_proxy_image_prefix="docker.io/openshift/" \
                         -e openshift_hosted_logging_hostname="kibana.127.0.0.1.nip.io"           \
                         -e openshift_logging_master_public_url="https://localhost:8443"          \
                         -e openshift_master_logging_public_url="https://kibana.127.0.0.1.nip.io" \
                         -e openshift_logging_use_mux=True                                        \
                         -e openshift_logging_mux_allow_external=True                             \
                         -e openshift_logging_es_allow_external=True                              \
                         -e openshift_logging_es_ops_allow_external=True                          \
                         ${EXTRA_EVARS:-} \
                         ${playbook} \
                         ${logging_extras} \
                         --skip-tags=update_master_config
    - type: "script"
      title: "run logging tests"
      repository: "origin-aggregated-logging"
      script: |-
        KUBECONFIG=/etc/origin/master/admin.kubeconfig TEST_ONLY=true SKIP_TEARDOWN=true JUNIT_REPORT=true make test
  system_journals:
    - origin-master.service
    - origin-master-api.service
    - origin-master-controllers.service
    - origin-node.service
    - openvswitch.service
    - ovs-vswitchd.service
    - ovsdb-server.service
    - etcd.service
    - systemd-journald.service
  artifacts:
    - "/data/src/github.com/openshift/origin-aggregated-logging/_output/scripts"
