---
parent: 'common/test_cases/origin_minimal.yml'
overrides:
  junit_analysis: False
extensions:
  actions:
    - type: "script"
      title: "run test-cmd"
      repository: "origin"
      script: |-
        OS_BUILD_ENV_DOCKER_ARGS='-v /tmp/etcd:/tmp/openshift/test-cmd/etcd' OS_TMPFS_REQUIRED=true OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/scripts OS_BUILD_ENV_TMP_VOLUME='/tmp' hack/env JUNIT_REPORT='true' make test-cmd -k