---
parent: 'common/test_cases/origin_release.yml'
extensions:
  actions:
    - type: "script"
      title: "run integration tests"
      repository: "origin"
      timeout: 3600
      script: |-
        OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64/integration.test hack/env make build-integration-test
        OPENSHIFT_SKIP_BUILD='true' JUNIT_REPORT='true' make test -o check -o build -k