---
children:
  - "test_branch_origin_check"
  - "test_branch_origin_cross"
  - "test_branch_origin_integration"
  # - "test_branch_origin_extended_conformance_install"
  - "test_branch_origin_extended_conformance_install_update"
  - "test_branch_origin_extended_networking_minimal"
  - "test_branch_origin_extended_conformance_gce"
  - "push_origin_release"
  - "ami_build_origin_int_rhel_build"