---
parent: 'common/test_cases/origin_release.yml'
overrides:
  timer: 'H H * * *'
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        JUNIT_REPORT='true' make test-extended SUITE=core FOCUS="\[builds\]"